"""Act 3-4 strings (EN + fr_CA draft). Run once; existing keys are left alone."""
from loc_helper import add

add("items", [
    ("item.projector_key.name", "Projector Key", "Clé du projecteur"),
    ("item.projector_key.desc", "A small brass key. The tag reads: THEATRE – PROJ.", "Une petite clé de laiton. L’étiquette indique : AMPHI – PROJ."),
    ("item.sanguine_key.name", "Sanguine Key", "Clé sanguine"),
    ("item.sanguine_key.desc", "A red lacquered key stamped with a feather and the word SANGUINE.", "Une clé laquée rouge frappée d’une plume et du mot SANGUIN."),
    ("item.crayon_drawing.name", "The Drawing", "Le dessin"),
    ("item.crayon_drawing.desc", "A child’s crayon drawing of a room with a high window and a man in white. It was folded very small.", "Un dessin d’enfant aux crayons de cire : une pièce, une haute fenêtre et un homme en blanc. Il était plié tout petit."),
    ("item.f08_journal.name", "Director’s Journal", "Journal du directeur"),
    ("item.f08_journal.desc", "A leather journal, the last pages torn out.", "Un journal relié de cuir, les dernières pages arrachées."),
    ("item.f09_label.name", "Pharmacy Label", "Étiquette de pharmacie"),
    ("item.f09_label.desc", "A printed label peeled from a pill bottle.", "Une étiquette imprimée décollée d’un flacon."),
    ("item.f10_case_slide.name", "Lecture Slide", "Diapositive de cours"),
    ("item.f10_case_slide.desc", "A glass slide in a cardboard frame: CASE STUDY.", "Une diapositive de verre dans un cadre de carton : ÉTUDE DE CAS."),
    ("item.f11_registry.name", "Morgue Registry Page", "Page du registre de la morgue"),
    ("item.f11_registry.desc", "A page from the 1976 morgue registry.", "Une page du registre de la morgue de 1976."),
    ("item.f12_tape.name", "Tape: Last Night", "Cassette : hier soir"),
    ("item.f12_tape.desc", "A cassette in my own handwriting. I don’t remember recording it.", "Une cassette annotée de ma main. Je ne me souviens pas de l’avoir enregistrée."),
])

books = [
    ("On the Temperaments", "Des tempéraments"),
    ("The Hysterical Child", "L’enfant hystérique"),
    ("Grief and Its Cures", "Le deuil et ses remèdes"),
    ("A Treatise on Insomnia", "Traité de l’insomnie"),
    ("The Burned Hand", "La main brûlée"),
    ("Forgetting as Medicine", "L’oubli comme remède"),
    ("Small Fires", "Petits feux"),
]
topics = [
    ("Admission and first interview", "Admission et premier entretien"),
    ("The night terrors", "Les terreurs nocturnes"),
    ("The imaginary sister", "La sœur imaginaire"),
    ("Isolation therapy", "Thérapie d’isolement"),
    ("Induced forgetting", "Oubli provoqué"),
    ("Prognosis", "Pronostic"),
]

add("puzzles", [(f"book.title.{i}", e, f) for i, (e, f) in enumerate(books)]
    + [(f"slide.topic.{i}", e, f) for i, (e, f) in enumerate(topics)] + [
    ("slide.pair", "“{a}” comes just before “{b}”.", "« {a} » vient juste avant « {b} »."),
    ("puzzle.p14.name", "Library Shelf", "Rayon de la bibliothèque"),
    ("puzzle.p14.hint", "Pick a book from the cart, then a gap on the shelf. Then push the shelf.", "Choisissez un livre sur le chariot, puis une place sur le rayon. Puis poussez le rayon."),
    ("puzzle.p14.push", "Push the shelf", "Pousser le rayon"),
    ("puzzle.p14.wrong", "The shelf doesn’t move. Something is out of place.", "Le rayon ne bouge pas. Quelque chose n’est pas à sa place."),
    ("puzzle.p15.name", "Pharmacy Scale", "Balance de la pharmacie"),
    ("puzzle.p15.hint", "Put weights on the pans until the scale balances at the prescribed dose.", "Placez des poids sur les plateaux jusqu’à ce que la balance s’équilibre à la dose prescrite."),
    ("puzzle.p15.weigh", "Release the beam", "Libérer le fléau"),
    ("puzzle.p15.total", "Total: {g} g", "Total : {g} g"),
    ("puzzle.p15.left", "Left", "Gauche"),
    ("puzzle.p15.right", "Right", "Droite"),
    ("puzzle.p15.off", "Off", "Retiré"),
    ("puzzle.p15.wrong", "The beam tips and the pan clatters.", "Le fléau bascule et le plateau claque."),
    ("puzzle.p16.name", "Slide Projector", "Projecteur de diapositives"),
    ("puzzle.p16.hint", "Load the slides into the carousel in lecture order.", "Chargez les diapositives dans le carrousel dans l’ordre du cours."),
    ("puzzle.p16.run", "Run the projector", "Lancer le projecteur"),
    ("puzzle.p16.slot", "Slot {n}", "Case {n}"),
    ("puzzle.p16.wrong", "The images flicker past. They make no sense in this order.", "Les images défilent. Dans cet ordre, elles n’ont aucun sens."),
    ("puzzle.p17.name", "Director’s Safe", "Coffre du directeur"),
    ("puzzle.p18.name", "Grandfather Clock", "Horloge grand-père"),
    ("puzzle.p18.hint", "Set the hands, then pull the chain.", "Réglez les aiguilles, puis tirez la chaîne."),
    ("puzzle.p18.hour", "Hour hand", "Petite aiguille"),
    ("puzzle.p18.minute", "Minute hand", "Grande aiguille"),
    ("puzzle.p18.pull", "Pull the chain", "Tirer la chaîne"),
    ("puzzle.p18.wrong", "The clock strikes, once, too loud.", "L’horloge sonne un coup, trop fort."),
    ("puzzle.p19.name", "Morgue Drawers", "Tiroirs de la morgue"),
    ("puzzle.p19.hint", "Open the drawer the registry gives.", "Ouvrez le tiroir indiqué par le registre."),
    ("puzzle.p19.drawer", "{n}", "{n}"),
    ("puzzle.p19.wrong", "Empty. The steel rattles in the dark.", "Vide. L’acier résonne dans le noir."),
    ("puzzle.p20.name", "Humors Panel", "Panneau des humeurs"),
    ("puzzle.p20.hint", "Put each temperament key in the slot of its season.", "Placez chaque clé de tempérament dans la fente de sa saison."),
    ("puzzle.p20.turn", "Turn the keys", "Tourner les clés"),
    ("puzzle.p20.wrong", "The keys won’t turn together.", "Les clés refusent de tourner ensemble."),
    ("puzzle.p20.need_keys", "Four keyholes. I need all four temperament keys.", "Quatre serrures. Il me faut les quatre clés de tempérament."),
    ("season.spring", "Spring", "Printemps"),
    ("season.summer", "Summer", "Été"),
    ("season.autumn", "Autumn", "Automne"),
    ("season.winter", "Winter", "Hiver"),
    ("element.air", "air", "air"),
    ("element.fire", "fire", "feu"),
    ("element.earth", "earth", "terre"),
    ("element.water", "water", "eau"),
    ("temperament.choleric", "Choleric", "Colérique"),
    ("temperament.melancholic", "Melancholic", "Mélancolique"),
    ("temperament.phlegmatic", "Phlegmatic", "Flegmatique"),
    ("temperament.sanguine", "Sanguine", "Sanguin"),
    ("puzzle.p21.name", "My File", "Mon dossier"),
    ("puzzle.p21.hint", "Put each piece of my life where it belongs. Then close the file.", "Remettez chaque morceau de ma vie à sa place. Puis fermez le dossier."),
    ("puzzle.p21.seal", "Close the file", "Fermer le dossier"),
    ("puzzle.p21.confirm", "Close the file? I won’t be able to change it.", "Fermer le dossier ? Je ne pourrai plus le modifier."),
    ("puzzle.p21.empty", "(missing)", "(manquant)"),
])

reading_line = "{t%d} ......... {c%d}"
add("documents", [
    ("doc.reading_list.title", "Reading List", "Liste de lecture"),
    ("doc.reading_list.body",
     "DIRECTOR’S READING LIST – return to shelf D by call number\n\n" + "\n".join(reading_line % (i, i) for i in range(5)),
     "LISTE DE LECTURE DU DIRECTEUR – remettre au rayon D par cote\n\n" + "\n".join(reading_line % (i, i) for i in range(5))),
    ("doc.reading_list.body_easy",
     "DIRECTOR’S READING LIST – return to shelf D, lowest number first\n\n" + "\n".join(reading_line % (i, i) for i in range(3)),
     "LISTE DE LECTURE DU DIRECTEUR – remettre au rayon D, plus petite cote d’abord\n\n" + "\n".join(reading_line % (i, i) for i in range(3))),
    ("doc.reading_list.body_hard",
     "DIRECTOR’S READING LIST – return to shelf D by call number\n\n" + "\n".join(reading_line % (i, i) for i in range(7)),
     "LISTE DE LECTURE DU DIRECTEUR – remettre au rayon D par cote\n\n" + "\n".join(reading_line % (i, i) for i in range(7))),
    ("doc.prescription.title", "Prescription", "Ordonnance"),
    ("doc.prescription.body", "Rx – Patient L.\nChloral, {dose} g. Weigh exactly. Night dose only.\n– Dir.", "Rx – Patient L.\nChloral, {dose} g. Peser exactement. Dose de nuit seulement.\n– Dir."),
    ("doc.prescription.body_hard", "Rx – Patient L.\nChloral, {dose} g, weighed exactly. The small weights are lost: use the 1, 3, 9 and 27, on either pan.\n– Dir.", "Rx – Patient L.\nChloral, {dose} g, pesé exactement. Les petits poids sont perdus : utilisez le 1, le 3, le 9 et le 27, sur l’un ou l’autre plateau.\n– Dir."),
    ("doc.f09_label.title", "Pharmacy Label", "Étiquette de pharmacie"),
    ("doc.f09_label.body", "CENTRE HOSPITALIER SAINTE-ODILE – UNITÉ 4\nLAVOIE, MATHIEU – Room 12\nClonazepam 0.5 mg – at bedtime\nDispensed: 1998-03-02", "CENTRE HOSPITALIER SAINTE-ODILE – UNITÉ 4\nLAVOIE, MATHIEU – Chambre 12\nClonazépam 0,5 mg – au coucher\nServi le : 1998-03-02"),
    ("doc.lecture_notes.title", "Lecture Notes", "Notes de cours"),
    ("doc.lecture_notes.body", "LECTURE: PATIENT L., A CASE OF TRAUMATIC FORGETTING\nSlides, in order:\n1. {t0}\n2. {t1}\n3. {t2}\n4. {t3}\n5. {t4}\n6. {t5}", "COURS : PATIENT L., UN CAS D’OUBLI TRAUMATIQUE\nDiapositives, dans l’ordre :\n1. {t0}\n2. {t1}\n3. {t2}\n4. {t3}\n5. {t4}\n6. {t5}"),
    ("doc.lecture_notes.body_hard", "LECTURE: PATIENT L., A CASE OF TRAUMATIC FORGETTING\nMy notes are out of order. What I remember:\n{p0}\n{p1}\n{p2}\n{p3}\n{p4}", "COURS : PATIENT L., UN CAS D’OUBLI TRAUMATIQUE\nMes notes sont en désordre. Ce dont je me souviens :\n{p0}\n{p1}\n{p2}\n{p3}\n{p4}"),
    ("doc.slide_overlay.title", "On the Screen", "Sur l’écran"),
    ("doc.slide_overlay.body", "Two slides overlap on the screen. Where the shadows cross, four numbers stand out:\n\n{d0}  {d1}  {d2}  {d3}", "Deux diapositives se superposent à l’écran. Là où les ombres se croisent, quatre chiffres ressortent :\n\n{d0}  {d1}  {d2}  {d3}"),
    ("doc.f10_case_slide.title", "Case Study: Patient L.", "Étude de cas : patient L."),
    ("doc.f10_case_slide.body", "CASE STUDY: PATIENT L. (1976–1981)\nMale, admitted age 9 after a fatal house fire. Total amnesia for the event. Persistent belief that the deceased sister is alive and \"lost in the building\".\nOutcome: discharged 1981. Readmitted as an adult, 1998.", "ÉTUDE DE CAS : PATIENT L. (1976–1981)\nGarçon, admis à 9 ans après un incendie mortel. Amnésie totale de l’événement. Croit fermement que sa sœur décédée est vivante et « perdue dans le bâtiment ».\nIssue : congé en 1981. Réadmis à l’âge adulte en 1998."),
    ("doc.f08_journal.title", "Director’s Journal", "Journal du directeur"),
    ("doc.f08_journal.body", "October 1979. The Lavoie boy asked me again where his sister sleeps. I told him the truth for the first time. He looked at me as if I had struck him, then asked again, politely, as if the question were new. The mind protects what it cannot carry. I have decided we will stop telling him.", "Octobre 1979. Le petit Lavoie m’a encore demandé où dort sa sœur. Pour la première fois, je lui ai dit la vérité. Il m’a regardé comme si je l’avais frappé, puis il a reposé la question, poliment, comme si elle était nouvelle. L’esprit protège ce qu’il ne peut pas porter. J’ai décidé que nous cesserions de le lui dire."),
    ("doc.clock_note.title", "Note on the Clock", "Note sur l’horloge"),
    ("doc.clock_note.body", "He stopped every clock in the house at the hour it happened. Wind this one and it will open.", "Il a arrêté toutes les horloges de la maison à l’heure où c’est arrivé. Remontez celle-ci et elle s’ouvrira."),
    ("doc.clock_note.body_easy", "He stopped every clock at the hour of the fire, the time in the newspaper clipping. Set this one to it.", "Il a arrêté toutes les horloges à l’heure de l’incendie, celle de la coupure de journal. Réglez celle-ci à cette heure."),
    ("doc.clock_note.body_hard", "Time stopped when the farmhouse burned. Make it stop again.", "Le temps s’est arrêté quand la ferme a brûlé. Arrêtez-le de nouveau."),
    ("doc.death_registry.title", "Death Registry", "Registre des décès"),
    ("doc.death_registry.body", "MORGUE REGISTRY – MARCH 1976\nDrawer {d0}: Male, 71. Heart.\nDrawer {d1}: Female, 64. Pneumonia.\nDrawer {d2}: Female, 6. Burns – farmhouse fire, 4th Range. Name not entered.\nDrawer {d3}: Male, 45. Drowning.\nDrawer {d4}: Male, 82. Age.", "REGISTRE DE LA MORGUE – MARS 1976\nTiroir {d0} : Homme, 71 ans. Cœur.\nTiroir {d1} : Femme, 64 ans. Pneumonie.\nTiroir {d2} : Fille, 6 ans. Brûlures – incendie de ferme, 4e Rang. Nom non inscrit.\nTiroir {d3} : Homme, 45 ans. Noyade.\nTiroir {d4} : Homme, 82 ans. Vieillesse."),
    ("doc.death_registry.body_hard", "MORGUE REGISTRY – MARCH 1976\nDrawer {d0}: M, 71. Cardiac.\nDrawer {d1}: F, 64. Pulmonary.\nDrawer {d2}: F, 6. Smoke.\nDrawer {d3}: M, 45. Water.\nDrawer {d4}: M, 82. –", "REGISTRE DE LA MORGUE – MARS 1976\nTiroir {d0} : H, 71. Cardiaque.\nTiroir {d1} : F, 64. Pulmonaire.\nTiroir {d2} : F, 6. Fumée.\nTiroir {d3} : H, 45. Eau.\nTiroir {d4} : H, 82. –"),
    ("doc.f11_registry.title", "Registry Page (1976)", "Page du registre (1976)"),
    ("doc.f11_registry.body", "The whole year, every name. No LAVOIE. No Claire. Whoever she was, she was never brought here.", "Toute l’année, chaque nom. Aucun LAVOIE. Aucune Claire. Qui qu’elle soit, elle n’a jamais été amenée ici."),
    ("doc.humors_mural.title", "The Four Humors", "Les quatre humeurs"),
    ("doc.humors_mural.body", "The mural, as it was painted:\nCHOLERIC – yellow bile – fire – SUMMER\nMELANCHOLIC – black bile – earth – AUTUMN\nPHLEGMATIC – phlegm – water – WINTER\nSANGUINE – blood – air – SPRING", "La murale, telle qu’elle a été peinte :\nCOLÉRIQUE – bile jaune – feu – ÉTÉ\nMÉLANCOLIQUE – bile noire – terre – AUTOMNE\nFLEGMATIQUE – flegme – eau – HIVER\nSANGUIN – sang – air – PRINTEMPS"),
    ("doc.humors_mural.body_hard", "The mural shows four figures. A man red with anger stands in a wheat field under a hot sun. A pale woman gathers fallen leaves. A sleeper lies by a frozen river. A laughing boy runs among blossoms.", "La murale montre quatre figures. Un homme rouge de colère se tient dans un champ de blé sous un soleil brûlant. Une femme pâle ramasse des feuilles mortes. Un dormeur est étendu près d’une rivière gelée. Un garçon rieur court parmi les fleurs."),
    ("doc.mural_damaged.title", "The Mural", "La murale"),
    ("doc.mural_damaged.body", "Water has run down the wall for years. Four painted figures, too faded to read.", "L’eau a coulé sur le mur pendant des années. Quatre figures peintes, trop effacées pour être lues."),
    ("doc.vault_rules.title", "Archive Instructions", "Consignes des archives"),
    ("doc.vault_rules.body", "PATIENT FILES ARE TO BE KEPT IN ORDER OF EVENTS. A file closed out of order will be returned to the ward.", "LES DOSSIERS DES PATIENTS DOIVENT ÊTRE CLASSÉS DANS L’ORDRE DES ÉVÉNEMENTS. Un dossier fermé dans le désordre sera renvoyé à l’unité."),
    ("doc.claire_hint.title", "A Note in My Writing", "Une note de ma main"),
    ("doc.claire_hint.body", "Every night I run from him. Maybe the door was never the way out. Next time, when he comes, I will put the whole file together, and I will stay.", "Chaque nuit, je le fuis. Peut-être que la porte n’a jamais été la sortie. La prochaine fois, quand il viendra, je remettrai tout le dossier en ordre, et je resterai."),
])

add("tapes", [
    ("tape.04_director.title", "Tape: Director’s Dictation", "Cassette : dictée du directeur"),
    ("tape.04_director.line1", "Director: Notes on patient L., November 1976.", "Directeur : Notes sur le patient L., novembre 1976."),
    ("tape.04_director.line2", "Director: He sleeps with his shoes on, by the door. He says he is waiting for someone to come and get him.", "Directeur : Il dort avec ses souliers, près de la porte. Il dit qu’il attend que quelqu’un vienne le chercher."),
    ("tape.04_director.line3", "Director: The orderlies say he calls the night man by his sister’s name.", "Directeur : Les préposés disent qu’il appelle l’homme de nuit du nom de sa sœur."),
    ("tape.05_last_night.title", "Tape: Last Night", "Cassette : hier soir"),
    ("tape.05_last_night.line1", "Mathieu: It’s me. It’s… it’s the twentieth of March. Ninety-eight.", "Mathieu : C’est moi. C’est… le 20 mars. Quatre-vingt-dix-huit."),
    ("tape.05_last_night.line2", "Mathieu: Dr. Bouchard says to record what I remember before it goes. So.", "Mathieu : La Dre Bouchard dit d’enregistrer ce dont je me souviens avant que ça parte. Alors."),
    ("tape.05_last_night.line3", "Mathieu: I had the matches. Claire wanted to see the little fire. I said I’d be careful.", "Mathieu : C’est moi qui avais les allumettes. Claire voulait voir le petit feu. J’ai dit que je ferais attention."),
    ("tape.05_last_night.line4", "Mathieu: (a long silence) Tomorrow I won’t remember saying this.", "Mathieu : (un long silence) Demain, je ne me souviendrai pas de l’avoir dit."),
])
