"""Act 3-4 room, ending and menu strings (EN + fr_CA draft). Existing keys are left alone."""
from loc_helper import add

add("rooms", [
    ("rooms.u01.name", "Upper Hall", "Grand couloir de l’étage"),
    ("rooms.u02.name", "Library", "Bibliothèque"),
    ("rooms.u03.name", "Reading Room", "Salle de lecture"),
    ("rooms.u04.name", "Pharmacy", "Pharmacie"),
    ("rooms.u05.name", "Observation Theatre", "Amphithéâtre d’observation"),
    ("rooms.u06.name", "Director’s Quarters", "Appartement du directeur"),
    ("rooms.b02.name", "Basement Corridor", "Couloir du sous-sol"),
    ("rooms.b03.name", "Morgue", "Morgue"),
    ("rooms.b04.name", "Treatment Room", "Salle de traitement"),
    ("rooms.b05.name", "Archive Antechamber", "Antichambre des archives"),
    ("rooms.b06.name", "Archive Vault", "Chambre forte des archives"),
    ("rooms.b07.name", "Ward Zero", "Aile Zéro"),
    ("rooms.u01.portrait", "A portrait of the Director. Someone has scratched out the eyes.", "Un portrait du directeur. Quelqu’un lui a gratté les yeux."),
    ("rooms.u02.shelf_d", "Shelf D. Gaps where books should be. The whole bookcase sits oddly far from the wall.", "Le rayon D. Des trous là où devraient être des livres. Toute la bibliothèque est étrangement décollée du mur."),
    ("rooms.u02.cart.solved", "The shelf has swung open. The cart is empty.", "Le rayon s’est ouvert. Le chariot est vide."),
    ("rooms.u04.scale.solved", "The scale stands level. The dose is measured.", "La balance est à l’équilibre. La dose est pesée."),
    ("rooms.u05.projector.locked", "The projector’s cabinet is locked. A small keyhole: PROJ.", "Le meuble du projecteur est verrouillé. Une petite serrure : PROJ."),
    ("rooms.u05.projector.solved", "The projector clicks and hums. The last image stays on the screen.", "Le projecteur cliquette et ronronne. La dernière image reste à l’écran."),
    ("rooms.u05.screen.blank", "A blank screen, grey with dust.", "Un écran vide, gris de poussière."),
    ("rooms.u06.safe.solved", "The safe stands open and empty.", "Le coffre est ouvert et vide."),
    ("rooms.u06.clock.solved", "The clock has stopped again at the same time. The panel beside it is open.", "L’horloge s’est de nouveau arrêtée à la même heure. Le panneau à côté est ouvert."),
    ("rooms.u06.dumbwaiter.locked", "A dumbwaiter hatch, bolted. The bolt is wired to the clock.", "Une trappe de monte-plats, verrouillée. Le verrou est relié à l’horloge."),
    ("rooms.u06.session_1976", "A boy sits across the desk from the Director, swinging his legs. “Where does Claire sleep?” he asks. The Director writes something down and does not answer.", "Un garçon est assis face au directeur et balance les jambes. « Où est-ce qu’elle dort, Claire ? » demande-t-il. Le directeur note quelque chose et ne répond pas."),
    ("rooms.u06.resonant", "The armchair hums. It is just the right height for a child.", "Le fauteuil bourdonne. Il est juste à la bonne hauteur pour un enfant."),
    ("rooms.b01.basement.locked", "The basement door is bolted from the other side.", "La porte du sous-sol est verrouillée de l’autre côté."),
    ("rooms.b02.treatment.locked", "TREATMENT. A red keyhole stamped with a feather.", "TRAITEMENT. Une serrure rouge frappée d’une plume."),
    ("rooms.b02.ward_zero.locked", "A bare wall. I could swear there was a door here.", "Un mur nu. J’aurais juré qu’il y avait une porte ici."),
    ("rooms.b03.drawers.solved", "The drawer stays open. It is empty now.", "Le tiroir reste ouvert. Il est vide maintenant."),
    ("rooms.b03.drawers_1976", "Twelve drawers, all closed, all clean. The one I want has no name card. It is empty.", "Douze tiroirs, tous fermés, tous propres. Celui que je cherche n’a pas d’étiquette. Il est vide."),
    ("rooms.b03.resonant", "The steel slab hums under my hand. It smells of smoke.", "La table d’acier bourdonne sous ma main. Elle sent la fumée."),
    ("rooms.b04.panel.solved", "The four keys stay turned. Somewhere a heavy lock gives way.", "Les quatre clés restent tournées. Quelque part, une lourde serrure cède."),
    ("rooms.b04.resonant", "The treatment chair hums. The straps are buckled around nothing.", "Le fauteuil de traitement bourdonne. Les sangles sont bouclées sur le vide."),
    ("rooms.b05.vault.locked", "A vault door with four keyholes painted in four colours. None of them turns.", "Une porte blindée avec quatre serrures peintes de quatre couleurs. Aucune ne tourne."),
    ("rooms.b06.file.sealed", "My file is closed. Somewhere behind me, a door opens that was not there before.", "Mon dossier est fermé. Quelque part derrière moi, une porte s’ouvre là où il n’y en avait pas."),
])

add("ui", [
    ("ui.menu.new_game_plus", "New Game+", "Nouvelle partie+"),
    ("ending.relapse.title", "Relapse", "Rechute"),
    ("ending.relapse.body", "The door opens onto the Dayroom. The radio hisses. The dictaphone is in my hand, and a child’s voice says: “Mathieu… viens me chercher.” I have been here before.", "La porte s’ouvre sur la salle commune. La radio grésille. J’ai le dictaphone à la main, et une voix d’enfant dit : « Mathieu… viens me chercher. » Je suis déjà venu ici."),
    ("ending.discharge.title", "Discharge", "Congé"),
    ("ending.discharge.body", "Sunlight. A hospital room, 1998. Dr. Bouchard sits by the bed with a file on her knees. “Good morning, Mathieu. Do you know where you are?” For the first time, I do.", "Du soleil. Une chambre d’hôpital, 1998. La Dre Bouchard est assise près du lit, un dossier sur les genoux. « Bonjour, Mathieu. Savez-vous où vous êtes ? » Pour la première fois, je le sais."),
    ("ending.claire.title", "Claire", "Claire"),
    ("ending.claire.body", "I stop running. He walks up to me and lifts his hand to his face. Under the white mask is a nine-year-old boy, smelling of smoke. Behind him, a girl with a red ribbon. “It’s okay, Mathieu,” she says. “You can stop looking for me now.”", "J’arrête de courir. Il s’approche et porte la main à son visage. Sous le masque blanc, il y a un garçon de neuf ans qui sent la fumée. Derrière lui, une fillette au ruban rouge. « C’est correct, Mathieu, dit-elle. Tu peux arrêter de me chercher, maintenant. »"),
    ("ending.stats", "Fragments in place: {score} / 12   ·   Puzzles solved: {solved} / {total}   ·   Time: {time}", "Fragments à leur place : {score} / 12   ·   Énigmes résolues : {solved} / {total}   ·   Temps : {time}"),
    ("ending.ng_plus_unlocked", "New Game+ unlocked: new codes, and your Files carry over.", "Nouvelle partie+ débloquée : nouveaux codes, et vos dossiers sont conservés."),
    ("ending.to_title", "Return to title", "Retour au titre"),
])
